maintainer       "computerlyrik"
maintainer_email "chef-cookbooks@computerlyrik.de"
license          "Apache 2.0"
description      "Set up liquid feedback system"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.1.0"
depends   "database"
depends   "postgresql"
depends   "mercurial"
depends   "openssl"
#depends   "exim4-light"
